defaults: &defaults
  adapter: postgresql
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host: <%= ENV['POSTGRESQL_ADDRESS'] %>
  encoding: utf8
  pool: <%= ENV["DB_POOL"] || 10 %>
  timeout: 5000
  reconnect: false

development:
  <<: *defaults
  database: <%= ENV['POSTGRESQL_DATABASE'] || 'citizen_budget_development' %>

test:
  <<: *defaults
  database: <%= ENV['POSTGRESQL_DATABASE'] || 'citizen_budget_test' %>

production:
  <<: *defaults
  database: <%= ENV['POSTGRESQL_DATABASE'] || 'citizen_budget_production' %>
